# Generated by Django 3.1.5 on 2021-01-31 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_advise', models.BooleanField()),
                ('can_upload_checksheets', models.BooleanField()),
                ('can_add_students', models.BooleanField()),
                ('can_assign_students', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
