# Generated by Django 3.1.5 on 2021-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='can_manage_faculty',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='can_manage_students',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
