# Generated by Django 3.1.5 on 2021-01-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksheetinstance',
            name='advisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advisement.advisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checksheetinstance',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checksheetinstance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisement.student'),
        ),
    ]
