# Generated by Django 3.1.5 on 2021-01-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0005_checksheetinstance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksheetinstance',
            name='notes',
            field=models.TextField(default='take notes here'),
            preserve_default=False,
        ),
    ]
