# Generated by Django 3.1.5 on 2021-01-30 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advisement', '0006_checksheetinstance_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecksheetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_advise', models.BooleanField()),
                ('can_upload_checksheets', models.BooleanField()),
                ('can_add_students', models.BooleanField()),
                ('can_assign_students', models.BooleanField()),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advisee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=10)),
                ('advisors', models.ManyToManyField(to='advisement.Advisor')),
                ('checksheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advisement.checksheettemplate')),
            ],
        ),
    ]
