# Generated by Django 3.1.5 on 2021-01-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0007_advisee_checksheettemplate_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
