# Generated by Django 3.1.5 on 2021-01-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('advisement', '0008_delete_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisee',
            name='advisors',
            field=models.ManyToManyField(to='accounts.Faculty'),
        ),
    ]
