# Generated by Django 3.1.5 on 2021-02-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('advisement', '0009_auto_20210131_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheetinstance',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty'),
        ),
        migrations.AlterField(
            model_name='checksheetinstance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisement.advisee'),
        ),
    ]
