# Generated by Django 3.1.5 on 2021-02-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0010_auto_20210201_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksheetinstance',
            name='template_filename',
        ),
        migrations.AddField(
            model_name='checksheetinstance',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='advisement.checksheettemplate'),
            preserve_default=False,
        ),
    ]
