# Generated by Django 3.1.5 on 2021-02-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0011_auto_20210201_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksheetinstance',
            old_name='student',
            new_name='advisee',
        ),
    ]
