# Generated by Django 3.1.5 on 2021-02-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0012_auto_20210201_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
