# Generated by Django 3.1.5 on 2021-03-15 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0013_auto_20210208_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksheetinstance',
            old_name='date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='checksheetinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
