# Generated by Django 3.1.5 on 2021-04-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0014_auto_20210315_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksheetinstance',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checksheetinstance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
