# Generated by Django 3.1.5 on 2021-04-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisement', '0015_auto_20210420_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checksheettemplate',
            name='data',
        ),
        migrations.AddField(
            model_name='checksheettemplate',
            name='data_file',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
