# Generated by Django 3.1.5 on 2021-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210330_1210'),
        ('advisement', '0017_auto_20210430_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisee',
            name='advisors',
            field=models.ManyToManyField(blank=True, to='accounts.Faculty'),
        ),
    ]
